### ISSUE TITLE
Status bar ignored of some/all? devices.

### ISSUE THREAD

**Issue by BradB111** [ApolloTVofficial/kamino#7] opened 2018-11-25 23:59 UTC
![image](https://user-images.githubusercontent.com/17122433/48986867-acc30480-f111-11e8-84d7-c82d439b5271.png)

Device: Oneplus 6T

Status bar ignored showing the series / movie image behind the status icons
(only an issue on brighter images where the white icons disappear)

**Comment by NBTX** [comment] 2018-11-26 03:03
Duplicate of https://github.com/ApolloTVofficial/kamino/issues/4

**Comment by BradB111** [comment] 2018-11-26 07:32
Please note this is not a duplicate of issue #4 as it refers to the status bar and NOT the navigation bar

**Comment by NBTX** [comment] 2018-11-26 09:37
My bad!

**Closed** 2018-12-08 16:06 UTC
Labels: bug
