### ISSUE TITLE
[Request] - Watched Episode Visual

### ISSUE THREAD

**Issue by JLDevUsr** [ApolloTVofficial/kamino#112] opened 2019-02-16 06:14 UTC
If there was some kind of notification that showed episodes you have already watched (could sync with trakt) as well as seasons you have finished watching that would be really cool. It would make it easier for navigating episodes and seasons you have already watched. It would also be useful for series you have finished entirely. I have included examples I quickly mocked up.

![examp 1](https://user-images.githubusercontent.com/47650360/52895269-b7b78f00-316c-11e9-9094-71e8fb323b4e.png)
![examp 2](https://user-images.githubusercontent.com/47650360/52895271-b7b78f00-316c-11e9-8c7f-48eab70fd30d.png)
![examp 3](https://user-images.githubusercontent.com/47650360/52895272-b8502580-316c-11e9-9ff0-cd0f2f8b4677.png)

Additional Feature To Mark Series, Seasons, and Episodes as Watched/Unwatched as well as to Favorite/Unfavorite Series without having to go into the series to click the Heart. (You would hold down on the series/season/episode to display the overlay)
![examp 4](https://user-images.githubusercontent.com/47650360/52895417-f5b5b280-316e-11e9-9c95-770abd4f294d.png)

**Comment by SpajicM** [comment] 2019-02-16 09:40
Duplicate of https://github.com/ApolloTVofficial/kamino/issues/88

**Closed** 2019-02-16 09:52 UTC
