### ISSUE TITLE
Making the app experience seamless by "having an option to locally cache metadata/links by "access frequency"

### ISSUE THREAD

**Issue by dscre** [ApolloTVofficial/kamino#152] opened 2019-03-15 08:26 UTC
(This request is somewhat similar to https://github.com/ApolloTVofficial/kamino/issues/126    but I come from a _very user oriented_ and _absolutely seamless app experience_ approach while _also being mindful of the bandwidth usage_.)

**Have a button on "Continue Watching" where you can cache certain no. of links/metadata to device.**

Heres an idea which can be applied/adapted to any page, not just the one I'm talking about. 
Let's say that there're _**two groups of users:**_ 
Those who majorly watch _more **new** content_ and 
Those who majorly watch the _stuff they **already started**_. 
It may seem that caching to local may be wasteful for the former but very useful for the latter. But I think that even for the former, caching can be useful _when done right_. See, the "**Continue Waching**" page is where the **two groups converge for maximum value of the "cache to device"**. 

Lets say you go to "**Continue Watching**" page. Here, you have lots of content to watch and so it'd be **waste of bandwidth to cache any content**. But...Suppose..
You sort by "**Access Frequency**". Then, you press a button to cache the top 20 episodes/content to the local device. This cache I think, will be most accessed by both groups. 

Lets say I'm on the "Continue Watching" page. 
I sort by "frequency" and I get "Series1,Series2,Series3" etc. Suppose 
Series1 has 10 episodes, 
Series2 has 15 episodes, 
Series3 has 20 episodes. 
All unwatched.

Lets say 20 is the maximum nos. of episode/content allowed by the app to cache.
I proceed to cache. 
Then the app will cache...
Series1-->10eps, 
Series2-->10 eps.

Suppose I watch 9 episodes by the end of the week. 
Afterwards I _go the "Continue Watching" page, sort by "frequency" and press "cache to local"_. 
Then the app will **modify the cache to purge watched episodes and add the next 9 episodes.**

**To not be wateful of this utility, maybe the "cache to local" is only available when the contents on the page is sorted by "frequency"**.

I think this will make the app NOT call the servers for most of its usage for most users and thus adding to the seamless experience.

Add to that, besides links, **maybe thumbnails and metadata can be cached too**. 
Lets say, I watch "Curb Your Enthusiasm", "Archer" frequently. 
These shows will be on the top of my page and the cached metadata/links will remain until I further refresh the cache. And _for episodes I watch repeatedly_, maybe have an option in the (episode/series?)page to disable purge of watched content.

Also, I don't mean "auto cache"; only cache when explicitly called for .

Maybe something along these lines can be worked out. Didn't think about movies though. 

These are just some thoughts about speeding up the app's _(series section)_ by using cache in a useful way for this scenario. Not into software or programming, so do excuse if I'm being naive about this.

Thanks.

**Comment by kevincosmos** [comment] 2019-03-15 09:00
Thanks for this suggestion, very well thought out.

I don't think I understand how this differs much from #126 besides saving the cached links locally?
Using your same scenario, assuming you go to watch S1E2, the server would automatically cache the next "X" episodes, and once you move on to S1E3 it would add the "X"+1 episode, so on and so forth so that your cached content is always "X" ahead of the current episode you are on.

Can you elaborate a bit further on how this differs from what's already suggested in 126?

**Comment by dscre** [comment] 2019-03-15 12:30
Hi! Thanks for the response. My suggestions are the _same as yours_,  albiet on a slightly _different scale_. I wanted the **cache to work in tandem with multiple sessions of browsing/watching**. In your case, the caching starts with a particular session(I guess?). You start watching an episode and then the app fetches further links in the background. 

I proposed a cache based on the **dynamic "Continue Watching" page.** A cache button on this page to only cache when told to.

We're always checking in new series, of which we'd like to continue watching some.
At any given period of time, I'm watching maybe a few shows. This dynamics would show in my "Continue Watching". I will sort this page by "frequency", factoring in "recently accessed". Then I'll cache so that **I may not need to call the servers for a week maybe**. (I'll explain this at the end. See NOTE).

Think of this caching as "_smart caching_" if you will. Also, this is only when you press the button i.e. no auto, no background. 

eg.: maybe I just want to check an episode with no intention of following up. Whereas in your case, if the toggle is on, you've no choice - "_just checking an episode_" will make the following episodes link cache -you've no finer control. I'm just proposing a little refined system. (By the way, I don't know any formula to perfectly fit in my case either)

**A SCENARIO:**
I'm continuing watching three shows in a week. 
[**Week#1**](https://imgur.com/uO5skFV): Total episodes remaining (unwatched) 30 episodes. 
I'll cache. **In this week, if I only watch these 3 shows, theres no need to call for the servers in that week.**
[**Week#5**](https://imgur.com/OBEVm5L): Based on my new discovery, the page has changed, and now if I cache again, I'm more or less fine for this week too **without calling the servers**.
 This is just to give an idea. In real case, you may start watching a new show, But for your regular pattern, the cache does help somewhat. 

NOTE: Suppose **Week#1** **GoT new season** releases_. It wont be cached automatically. If I jump to watching the new season, while still having previous unwatched episodes, it'll fetch from the servers. But if I intend to cache the new season too, I can. Suppose theres 8 episodes in new season, caching will turn it like [this](https://imgur.com/u87WzIF).

PS: Theres flaws in my idea/argument sure. For eg. Among "similar frequency" series, I know recently accessed should be higher up. Don't know by how much.

PS2: Sometime back I did chat on Discord, some incomprehensible things. I don't have much input, so don't chat now.  By the way,  I myself am not very clear about the implementation. These are just thoughts. 
Sorry if I'm not clearer than before or if I just repeated the same thing. I'll _try_ to log on Discord if you need any further thoughts/clarification.

Thanks for reading.

**Comment by SpajicM** [comment] 2019-03-16 20:55
Hi, first off, thank you for a very elaborate explaination of the feature, we appreciate that.

One major reason why I don't like this is the button - we, further down the line atleast, want to provide users the seamless experience. No need to remember to press the button. 
We will try to do less waiting time, less concern with sources, caching for end-user.

In my opinion, caching one episode at the time is enough because you will rarely jump from episode 1 to episode 3, skipping episode 2 for no reason, while if you don't continue watching it's okay, we've only had a 1 "unused" call to server.

You mention how if you press the button, it will cache 30/50 episodes for the shows you watch and having no need to call the server the entire week. Server doesn't really care if it does 30 scrapes at once, or 30 scrapes spread out over 30 days, so that doesn't really matter.

In the end line, we would skip implementing such "more complex" algorithms for now anyway. We would rather go down the line that takes less effort for user (pressing the button) and for developers as well. 

For now 1 or 2 episode method looks like a win win for all, users, developers, server usage.

Thanks again for the suggestion!

**Comment by dscre** [comment] 2019-03-17 03:07
Thanks for the thoughts and clarification.
It certainly is complex and if a simple solution of 1 or 2 episodes work, theres no need to make it difficult. I understand.

Just want to clarify some points. This is lengthy as well. Please bear. Also, this isn't persuation, just clarification.
Feel free to close the topic if I've taken too much of time. I know I already did. 

**>**_Server doesn't really care if it does 30 scrapes at once, or 30 scrapes spread out over 30 days, so that doesn't really matter_.
I drink **10 packs of apple juice a week**. Theres a small store very near my house. I call and within a couple of minutes 2 juice packs are near my door. Now, I need to **call few times a week** to get through the week. But suppose the store introduces a **box containing 10 packs!** That would be wonderful!
**The store doesn't care if I call once a day or once a week. If I can order a full box once, its convenient for me.**
Furthermore, if I can ask to put a few mango juice packs in the box instead on the regular, I can do that too.
**Its about my convenience. Thats where I come from.** _(store's hasn't changed much)_

**>** _We would rather go down the line that takes less effort for user  (pressing the button) and for developers...._
Well I don't think why automation wouldn't work _here_. Maybe when the "by frequency" Continue Watching page changes, it can. Yes, the developers' work is increased for implementing a complex algorithm. _(But I hope you guys should atleast try this in the future, **if** you're convinced with the idea that is. Or something like this)_

**>**_we would skip implementing such "more complex" algorithms for now anyway._
All things are difficuit before they are easy.

**>**_For now 1 or 2 episode method looks like a win win for all, users, developers, server usage._
Agree. I just had ideas and presented them. I'm fine with what you do within your capacity. Besides, one should also factor in whether the benefits are significant for the effort put.

**Cheers!**

**Comment by kevincosmos** [comment] 2019-04-30 14:15
I'm going to close this as it's pretty much a duplicate of #126

**Closed by kevincosmos** 2019-04-30 14:15 UTC
