### ISSUE TITLE
Grid view in series season

### ISSUE THREAD

**Issue by DreighUpstairs** [ApolloTVofficial/kamino#208] opened 2019-04-29 01:58 UTC
An option to show episodes within a season in a grid view so you don't have to scroll so far to get to an episode (if you can even tell what episode you are actually on) and so you can easily overview episodes released to make finding the correct one faster. (This could also work with #88 so that you don't have to scroll past a bunch of already watched episodes to find a new one)

**Comment by kevincosmos** [comment] 2019-04-30 12:38
There are already plans in place for this :)

**Comment by kevincosmos** [comment] 2019-04-30 14:41
I'm going to close this as a duplicate of #27

**Closed by kevincosmos** 2019-04-30 14:41 UTC
