### ISSUE TITLE
Popular TV shows has movies not tv shows. 

### ISSUE THREAD

**Issue by JustAskDave** [ApolloTVofficial/kamino#95] opened 2019-01-30 01:30 UTC
**Describe the bug**
Section showing Popular TV shows has movies and not tv shows.

Also the Top Rated tv shows section has movie icons instead of tv show icons.

**Expected behavior:**
Would expect to see tv shows in Popular TV show section, and tv show icons on tv shows instead of movie icons.

**Actual behavior:**
As above

**Steps to Reproduce:**
Always showing

**Screenshots:**
![screenshot_20190130-112200](https://user-images.githubusercontent.com/45019570/51951985-6330c600-2482-11e9-8d7e-2d8d337e1d12.jpg)

**Device Information:**
 - Device: Samsung Tab A
 - OS: Android 7.1.1

**Additional context:**
Add any other context about the problem here including, where appropriate, error logs.
[

**Comment by SpajicM** [comment] 2019-01-30 15:45
Can't reproduce the issue.

![screenshot_20190130-115359](https://user-images.githubusercontent.com/21988220/51993088-79ed1200-24ae-11e9-9246-ed481e3ce3d8.png)

**Comment by Rowan-Paul** [comment] 2019-01-30 16:08
Isn't it this issue:
https://github.com/ApolloTVofficial/kamino/issues/84

**Comment by kevincosmos** [comment] 2019-02-10 20:31
This is a repeat of #84. Closing.

**Closed by kevincosmos** 2019-02-10 20:31 UTC
