### ISSUE TITLE
Favorites - Error when adding movie without image.

### ISSUE THREAD

**Issue by wjziv** [ApolloTVofficial/kamino#96] opened 2019-01-30 21:00 UTC
To reproduce an example, add "Pirate Radio USA (2006)" to favorites, and find it in the movies section of favorites.

The movie has no image associated with it. When added to the Favorites section, you're met with a red block, and yellow text running down the left side "Invalid argument(s)__________" repeated.

**Comment by FlyPigsFly** [comment] 2019-01-30 21:54
Duplicate of https://github.com/ApolloTVofficial/kamino/issues/86

**Comment by edmundackah** [comment] 2019-01-31 06:45
Am aware of this bug, currently looking into it

**Comment by NBTX** [comment] 2019-02-10 17:10
Closing as duplicate.

**Closed by NBTX** 2019-02-10 17:10 UTC
