### ISSUE TITLE
Links Found During Scraping

### ISSUE THREAD

**Issue by TittyMcTwister** [ApolloTVofficial/kamino#83] opened 2019-01-28 06:45 UTC
When scraping for sources it should show how many links have been found.

**Comment by kevincosmos** [comment] 2019-01-28 11:12
Do you mean during scraping? We either show you the results or tell you none have been found.

**Comment by BradB111** [comment] 2019-01-28 12:10
I believe this is to show the number of sources as they are found during scraping. (Updated real time)

So dialogue would read:

"Searching for sources: <X> Found "

Maybe this can be expanded to the following when RD is implemented.

"Searching for sources: <X> RD | <Y> Normal"

Or similar?

**Comment by FlyPigsFly** [comment] 2019-01-28 12:13
Related? https://github.com/ApolloTVofficial/kamino/issues/57

**Comment by TittyMcTwister** [comment] 2019-01-28 12:44
Ahh sorry didnt see #57 
But meant the same thing

**Comment by kevincosmos** [comment] 2019-02-10 21:00
Duplicate of 57. Closing.

**Closed by kevincosmos** 2019-02-10 21:00 UTC
Labels: enhancement
