### ISSUE TITLE
(Potentially Resolved - Awaiting Kamino Update) Authentication Failed Type 1

### ISSUE THREAD

**Issue by SilentDesigner** [ApolloTVofficial/kamino#114] opened 2019-02-17 15:22 UTC
Issue still persists when trying to play a movie even after rebooting phone and clearing app data.

Samsung Galaxy S9 Plus
Not rooted
Downloaded update from Apollo website
Android Pie One UI 1.0

**Comment by kevincosmos** [comment] 2019-02-17 15:38
Hi @SilentDesigner, Developers are aware of this issue and I have asked for an update. I will assign this defect to them so hopefully someone can provide an update on this.

Can you provide the following information:
- Phone
- Root status (rooted/not rooted)
- Where you downloaded the update from (Apollo's website, Auto Update, Filelinked)

Thanks

**Comment by Rowan-Paul** [comment] 2019-02-17 16:58
I've been using the app for a while without problems until yesterday evening I experienced this issue and after restarting it was fixed

*Version:* ApolloTV v1.3.3 (Build 103030)
*Phone:* Samsung Galaxy J3 (2017)
SM-J330FN (Unlocked)
Android 8.0.0 & Samsung Experience version 9.0

**Comment by SilentDesigner** [comment] 2019-02-17 17:16
I've tried restarting multiple times, but I still get the same issue with every movie, unfortunately.

**Comment by kevincosmos** [comment] 2019-02-17 17:55
> I've been using the app for a while without problems until yesterday evening I experienced this issue and after restarting it was fixed
> 
> _Version:_ ApolloTV v1.3.3 (Build 103030)
> _Phone:_ Samsung Galaxy J3 (2017)
> SM-J330FN (Unlocked)
> Android 8.0.0 & Samsung Experience version 9.0

Can you confirm if you made any changes to the app before this occured? You're the first person to report it happening randomly after working for a long period of time.

**Comment by kevincosmos** [comment] 2019-02-17 17:55
> I've tried restarting multiple times, but I still get the same issue with every movie, unfortunately.

Can you provide the info I asked for above? This will help devs to troubleshoot

**Comment by SilentDesigner** [comment] 2019-02-17 17:57
Sorry, I added it to the original post but here's the info:

Samsung Galaxy S9 Plus
Not rooted
Downloaded update from Apollo website
Android Pie One UI 1.0

**Comment by kevincosmos** [comment] 2019-02-17 18:03
Thanks, I'll need to wait for a Dev to provide feedback/an update for you

**Comment by Rowan-Paul** [comment] 2019-02-17 18:04
I've got manually select sources and detailed content information on, no trakt and I've customized the launchpad to only include popular TV and movies

But yeah using nothing else 

Guess it might be Samsung's skin (although I'm still using experience 9 and not 10(OneUI) like SilentDesigner

**Comment by kevincosmos** [comment] 2019-02-17 18:08
I don't think it's related to Samsung as others have reported it on non-Samsung devices, the initial suggestion was that it was maybe related to memory management holding on to some data, but I've not had an update on this in several days so I'll need to wait for an update.

**Comment by kevincosmos** [comment] 2019-02-18 15:56
@SilentDesigner Devs are currently investigating, in the meantime can you do the following:

Try going into your phone's settings and disable automatic date/time and disable automatic time zone. Then change the time to any time of your choosing. Then re-enable automatic date/time and automatic time zone. Reboot your phone and try the app again.

Can you let me know if this works please

**Comment by SilentDesigner** [comment] 2019-02-18 16:07
Surprisingly, that worked.  For the movies that I tried, two did not have any sources, and others found around two sources each.  But at least it's actually searching for sources now.

Thank you!

**Comment by kevincosmos** [comment] 2019-02-18 16:36
@SilentDesigner Perfect! We think we know the root cause and have a potential solution to implement. I'll keep this issue open until a fix is released and verified by others

**Comment by SpajicM** [comment] 2019-02-19 15:26
Fixed in #116

**Comment by NBTX** [comment] 2019-02-19 20:12
Fixed.

**Closed by NBTX** 2019-02-19 20:12 UTC
Labels: Bug, Planned/In Progress
