### ISSUE TITLE
Search results loading

### ISSUE THREAD

**Issue by SpajicM** [ApolloTVofficial/kamino#20] opened 2018-11-26 09:49 UTC
Instead of new search results overwriting the old ones as they're being loaded, old search results should be removed and replace with a loading spinner while new ones start appearing. Also #17 and #19

**Comment by ddivad** [comment] 2018-11-26 09:53
@SpajicM as this is a direct duplicate of #17 I'm going to close this in favour of that bug, and update the title and description accordingly. Thanks for reporting the issue though :)

**Closed** 2018-11-26 09:53 UTC
