### ISSUE TITLE
Android TV Interface/Navigation Issues

### ISSUE THREAD

**Issue by itstDames** [ApolloTVofficial/kamino#82] opened 2019-01-28 06:03 UTC
**Describe the bug**
A. Remote does not work at all
B. No ATV Launcher Icon
C. White Interface have light grey text

**Expected behavior:**
A. Cannot navigate unless I use a air mouse.
B. Have to go to Settings > Apps to find application
C. Darker Text

**Device Information:**
Sony TV X700D - Android TV 8

**Comment by kevincosmos** [comment] 2019-01-28 11:13
TV devices are not yet supported, you can use an Air Mouse as a workaround.
TV remote support is currently being looked at.
Closing issue.

**Closed by kevincosmos** 2019-01-28 11:13 UTC

**Comment by NBTX** [comment] 2019-02-23 09:34
(Duplicate of #111)
